### ISSUE TITLE
Je souhaite apporter mon aide

### ISSUE THREAD

**Issue by BauerArnaud** [covid-response-projects/covid-respirator#14]
Bonjour,

Je vous contacte de la part de Gabriel Moneyron qui contribue déjà au projet. J'aimerais également y participer. 
Je serais ravi de vous aider sur les aspects conception 3D et électronique. Je réside sur Nantes et possède une imprimante 3D, tout le nécessaire pour réaliser des circuits électroniques et bientôt une CNC.

Comment puis-je vous aider ?

**Comment by waxzce** [comment]
tu peux m'envoyer ton tel : 06 62 09 40 07 et je t'appel ?

**Comment by eliottvincent** [comment]
A rejoint le Slack.
