### ISSUE TITLE
Je suis sur Nantes et j'ai une imprimante 3D

### ISSUE THREAD

**Issue by kmorinCL** [covid-response-projects/covid-respirator#19]
Salut,

Je suis sur Nantes et j'ai une imprimante 3D (Alfawise U20, volume 30*30*40, plateau chauffant), donc si je peux aider, ce sera avec plaisir. J'ai pas mal de PLA, une bobine de PETG, et des échantillons de ABS.

Bon courage pour ce beau projet

**Comment by eliottvincent** [comment]
Salut, envoie moi un mail à dev [[at]] eliottvincent [[dot]] com 😉On a un Slack avec un channel dédié à nos demandes d'impression 3D.

**Comment by kmorinCL** [comment]
Done

**Comment by Shalf** [comment]
A rejoint le slack.
