### ISSUE TITLE
[Soft] be sure that every   pinMode(PIN_SERVO_PATIENT, OUTPUT); is OK

### ISSUE THREAD

**Issue by waxzce** [covid-response-projects/covid-respirator#28]

**Comment by jabby** [comment]
WIP here.
https://github.com/covid-response-projects/covid-respirator/pull/21

**Comment by dsferruzza** [comment]
I believe this is already handled by the Servo lib we use? → https://github.com/arduino-libraries/Servo/blob/master/src/avr/Servo.cpp#L241

**Comment by jabby** [comment]
I close the issue as it is handled by Servo lib.
Feel free to reopen if needed.

**Comment by waxzce** [comment]
but not for every pin, whiuch was my point

**Comment by dsferruzza** [comment]
I'm not sure to get your point actually... Both servos are OUTPUT thanks to the lib, right? Do we need more?

**Comment by jtanguy** [comment]
Yes, for the buttons, pressure sensor and buzzer. 
There is no pinMode set for any pin in the master branch atm

**Comment by jabby** [comment]
Ok I'm on it.

**Comment by jabby** [comment]
* Servo: :ok: thanks to the [lib](https://github.com/arduino-libraries/Servo/blob/master/src/avr/Servo.cpp#L241)
* Buttons: :ok: thanks to the lib ([here](https://github.com/rlogiacco/AnalogButtons/blob/master/AnalogButtons.h#L105) and [here](https://github.com/rlogiacco/AnalogButtons/blob/master/AnalogButtons.cpp#L34)) and to our code [here](https://github.com/covid-response-projects/covid-respirator/blob/master/src/arduino/respi_v0.cpp#L188)
* Pressure sensor: missing. `analogRead` does not set the pinMode to `INPUT`.
* Buzzer: not implemented yet.
