### ISSUE TITLE
Liste materiel

### ISSUE THREAD

**Issue by Pepeuch** [covid-response-projects/covid-respirator#29]
Bonjour, quelle est la liste du matériel nécessaire de façon à se préparer à la fabrication?
- taille moteur, le Kv
- contrôleur brushless quelle puissance
- servo numérique ou analogique quel couple
- composants
- arduino quel model, les copies seront seront elles prisent en charge ( sanguino et autre )

**Comment by eliottvincent** [comment]
Hello!

Je te propose de t'inviter à notre Slack pour voir où le projet en est. Tu peux me demander une invitation à dev at eliottvincent dot com.
