### ISSUE TITLE
Choosing the pressure sensor

### ISSUE THREAD

**Issue by Benhalor** [covid-response-projects/covid-respirator#3]
Hello,

Congratulations on your project. I'm impressed with how fast you're moving!
You said in the video that the pressure would be monitored by a pressure sensor. 

If you need help for choosing the pressure sensor, you can contact me : +33 (0)695358125

you said "et un capteur qui permette de mesurer la pression de plateau qui doit être maximum à 30cmH2O" : 

This one could fit : 
https://fr.farnell.com/honeywell/hscsaan001pdaa5/sensor-1psi-dual-axial-sip-5v/dp/1823226

it is 0 to 1 PSI which means 0 to 70.3 cmH2O
5V analog output
Made for medical application

Gabriel

**Comment by waxzce** [comment]
For the reccord, we did have a call with @Benhalor and solve many problmes thax to him

**Comment by pi-r-p** [comment]
Hello, 
I went through the electronic part (respi_V0.fzz) ( @hbs send me a link to the project) , same remarks... In french:

Le capteur MPX10GP n'est pas le meilleur. La plage est bonne (10kPa pour un respirateur, ça va, la pression usuelle montera au grand max à 5kPa ([d'après une doc médicale ici](https://www.srlf.org/wp-content/uploads/2020/03/2020-FP-Respi-3-Principes-ge%CC%81ne%CC%81raux-de-re%CC%81glage-des-modes-contro%CC%82le%CC%81s-et-assiste%CC%81s.pdf)), mais il ne faut pas prendre un modèle avec une sortie différentielle derrière, et encore moins mettre un AOP comme celui là derrière (lm741, ça s'alimente en +/- 15v si vous voulez en tirer qqch, et il faut gérer l'aspect différentiel). 

Nxp fait aussi des modèles plus récents avec électronique intégrée, qui te font une belle sortie rail to rail 0-5V. Typiquement https://www.nxp.com/docs/en/data-sheet/MPX5010.pdf , c'est déjà plus simple à cabler sur un arduino. Prendre un modèle avec tuyaux, dont un reste en l'air à la pression ambiante, typiquement MPX5010DP. L'amplification n'est plus nécessaire, on peut se contenter de baisser la ref anologique de l'ADC (AREF sur un arduino). 

Attention, il faut aussi créer une bonne référence de tension, et isoler la partie capteur/ADC du reste pour pas avoir un signal trop bruité. Sans séparation puissance/controle, le 5V risque de fluctuer à chaque mouvement des servomoteurs, et fausser la mesure de pression. Donc:
- on alimente en 9 ou 12volts
- on met derrière un régulateur 5V à découpage pour l'arduino et les servos (n'importe quel buck 5v trouvé sur le net)
- un régulateur 5v linéaire (un 7805) pour le capteur, avec quelques condos de découplage (470uF derrière le 7805, 100nF au plus proche de l'alim du capteur, soudé dessus de préférence si il n'est pas sur un circuit imprimé). 
- un régulateur 3.3v linéaire sur AREF (3.3v expoiterait mieux la dynamique de l'adc), pareil, avec des condos de découplage.

Et si c'est un capteur Nxp de cette série il faut une procédure de calibration initiale, car c'est pas un capteur super précis. Le capteur Honeywell suggéré par @Benhalor est deux fois plus cher, mais 10 fois plus précis... Mieux vaut prendre celui là !!

À confirmer par un médecin, mais la pression minimale à maintenir en fin d'expiration est importante aussi, d'après le doc dont j'ai mis le lien plus haut.

**Comment by Pepeuch** [comment]
Le prix d’un capteur même 10X plus cher est toujours mieux qu’une vie, le problème va être la livraison pour que cela arrive au plus vite, avec les mesures de confinements et donc de livraisons va être un nouveau dileme.

**Comment by Mefl** [comment]
@Benhalor a été intégré au slack
