### ISSUE TITLE
Other similar project

### ISSUE THREAD

**Issue by GMartigny** [covid-response-projects/covid-respirator#31]
Hi,
I found another project called [VentilAid](https://gitlab.com/Urbicum/ventilaid/) doing the same thing. They are from Poland, so I don't know if there's possible difference with other country legislation.

It could be a good thing to work with them or draw inspiration from their work.

**Comment by eliottvincent** [comment]
Hello, thanks for the link!

Since we're aware of this project, I'm considering this as handled, and I'm closing the issue.
