### ISSUE TITLE
Suspicious test

### ISSUE THREAD

**Issue by jlbirccyn** [covid-response-projects/covid-respirator#34]
Test here

https://github.com/covid-response-projects/covid-respirator/blob/bb0498889a6f3fb93348fc18bfb514d5adc137c7/src/arduino/respi_v0.cpp#L340

leads to execute the if section one more centieme than expected (according to the name of variable ```nbreCentiemeSecParInspi```) because ```currentCentieme``` starts at 0. It should be:

```
if (currentCentieme < nbreCentiemeSecParInspi) { 
```

**Comment by dsferruzza** [comment]
In the last two weeks the code architecture changed a lot and I believe this specific issue is now outdated, so I'm closing this! (Thanks for the reminder!)
