### ISSUE TITLE
Carte électronique projet covid-respirator

### ISSUE THREAD

**Issue by Yann-Emile** [covid-response-projects/covid-respirator#43]
Bonjour

Je suis technicien en électronique à l'IUT de Nantes, et j'ai appris l'existence de votre projet (covid-respirator) par l'intermédiaire d'un enseigmant de l'IUT.

J'ai une certaine expérience dans la conception et la fabrication de carte électronique, et j'ai
remarqué que vous avez commencé le routage d'un carte électronique pour votre projet.

Seriez-vous intéressé que je finalise le routage de cette carte pour favoriser l'avancement de 
votre projet ?

Cordialement.

Yann-Emile

**Comment by eliottvincent** [comment]
Hello!

Je peux t'inviter à notre Slack, à ton arrivée tu peux regarder dans le chan #electronique et envoyer un message à Emmanuel Feller qui lead la partie elect / soft. 
Envoie moi un mail à dev at eliottvincent dot com pour que je t'invite. À tout de suite.

e.
