### ISSUE TITLE
Youtube videos down ?

### ISSUE THREAD

**Issue by arthurlutz** [covid-response-projects/covid-respirator#69]
Hi it seems that the youtube videos are down. Changed accounts ? Deleted ? 

Can it help to have a mirror of these videos on peertube ?

**Comment by dolmen** [comment]
It looks like they are branding the project (Makair.life). Might be related.

The latest video seems to be reserved to those who have a YT account: https://www.youtube.com/watch?v=9OVCqwCGC-o

**Comment by eliottvincent** [comment]
Hello! We're switching to "low profile" mode in order to get work done and avoid media pressure. Hence switching the YouTube videos to "private". I hope you can understand.
