### ISSUE TITLE
How to contribute ?

### ISSUE THREAD

**Issue by tuxinoo** [covid-response-projects/covid-respirator#8]
Hi, 
I just discovered this project through a Devoxx's tweet including a video link with @waxzce presenting and explaining the objective of the project. How could I contribute (3D printing, developing, electronic, ...) ?
Regards

**Comment by valeriansaliou** [comment]
@waxzce

**Comment by Shalf** [comment]
Hi @tuxinoo,
Re: 3D printing. Are you in/near Nantes, France? Do you have at last one printer available, if so which one, please?
Thanks for your patience!

**Comment by tuxinoo** [comment]
Hi @Shalf,
I sent you an email.
