### ISSUE TITLE
Pourquoi plus aucune comm’ vidéo ??

### ISSUE THREAD

**Issue by tuxinoo** [covid-response-projects/covid-respirator#87]
Hello,
Je suivais le projet de près depuis le début et avais même souhaité apporter mon aide mais le besoin était surtout en besoin d’imprimante sur Nantes.
Aujourd’hui, je ne sais plus ce qu’il en est, plus de vidéos points d’avancement d’Adam 😕
Comment peut-on faire pour continuer à suivre l’avancée du projet ? L’esprit initial d’ouverture a-t-il disparu ?

**Comment by eliottvincent** [comment]
Hello! On se met en "low profile" pour se concentrer sur tout ce qu'il y a à faire et aussi pour éviter la pression médiatique. D'où les anciennes vidéo en mode "privé" et l'absence de points d'avancements. No news is good news 😉

Et nous gardons bien évidement notre esprit initial "community-driven" et "open-source".
